Aggiunta dei miei appunti (non ancora completi)
csunibo/ipim-ingegneria-del-software pull request #15
Opened 2024-05-16 10:02 UTC by JosephBoom02

2024-05-16 12:02 UTC, foxyseta requested changes
Ciau e grazie! Come specificato [nella nostra wiki](https://csunibo.github.io/wiki/raccolte-di-risorse/controlli-automatici/), il primo controllo automatico fallisce perché non tutti i file stanno usando `la-convenzione-kebab.case`. Usiamo le convenzioni di stile per mantenere tutte le repo ordinate.

Siccome sono tanti file, se non sai come fare per rinominarli tutti in un colpo solo fammi sapere che ci penso io (di solito uso [stdrename](https://csunibo.github.io/wiki/raccolte-di-risorse/controlli-automatici/)).

2024-05-17 07:25 UTC, JosephBoom02 commented
> Ciau e grazie! Come specificato [nella nostra wiki](https://csunibo.github.io/wiki/raccolte-di-risorse/controlli-automatici/), il primo controllo automatico fallisce perché non tutti i file stanno usando `la-convenzione-kebab.case`. Usiamo le convenzioni di stile per mantenere tutte le repo ordinate.
> 
> Siccome sono tanti file, se non sai come fare per rinominarli tutti in un colpo solo fammi sapere che ci penso io (di solito uso [stdrename](https://csunibo.github.io/wiki/raccolte-di-risorse/controlli-automatici/)).

Si, potrei farlo, ma dovrei poi cambiare il nome di ogni file immagine nel file .typst e questo mi toglierebbe molto tempo (credo). Magari per ora carico solo il pdf

2024-05-17 07:33 UTC, foxyseta commented
Ah non preoccuparti con trova e sostituisci penso di poter correggere il file `.typ` in modo abbastanza veloce. Se ti va bene forse ho tempo di provarci in questo fine settimana.

2024-05-17 07:52 UTC, JosephBoom02 commented
> Ah non preoccuparti con trova e sostituisci penso di poter correggere il file `.typ` in modo abbastanza veloce. Se ti va bene forse ho tempo di provarci in questo fine settimana.
> 
> Edit: addirittura siccome sei la nostra prima PR di contenuti scritti in Typst potremmo aggiungere la conversione automatica (Typst -> PDF) così che basti caricare solo il Typst su GitH*b e poi il pdf sia visibile su csunibo in automatico

Vai. va bene.

2024-05-17 13:09 UTC, foxyseta approved these changes

2024-05-17 13:14 UTC, foxyseta commented
Appena corretto i nomi (anche dentro al file Typst: ho riprovato a compilare e ancora funziona). Per ora come d'accordo ti accetto la PR sia con il `.typ` che con il `.pdf`. Appena aggiungiamo il supporto a Typst (https://github.com/csunibo/config/pull/47) rimuovo il PDF e per le prossime PR non servirà più caricarlo.

Grazie mille di nuovo!

2024-05-17 13:14 UTC, merged

2024-05-23 12:23 UTC, foxyseta commented
Ciao @JosephBoom02! Con l'uscita dell'immagine docker di [Alpine Linux 3.20](https://alpinelinux.org/posts/Alpine-3.20.0-released.html) (che contiene il pacchetto nativo per Typst), abbiamo aggiunto [la promessa compilazione automatica da `.typ` a `.pdf`](https://github.com/csunibo/config/pull/47). @samuelemusiani ha quindi rimosso il tuo PDF in 9a593ef, siccome è ora generato in automatico dal tuo `.typ`.

[Aggiorniamo la documentazione a breve](https://github.com/csunibo/csunibo.github.io/pull/52), così che si sappia che d'ora in poi caricare il `.typ` è sufficiente.